### PR TITLE
Read tumbprint from CircleCI OIDC endpoint TLS certificate instead of hardcoding it.

### PR DESCRIPTION
**Pull request by TonyLovesDevOps**
Does what it says on the tin.

Thanks for making this module!

### CODE REVIEW

**Comment by AlexSc** [comment]
Thank you for the kind words and for your contribution!

Because the thumbprint is a key part of establishing the chain of trust between AWS and whatever server is claiming to be CircleCI I'm a bit wary of exclusively supporting a trust-on-first-use mechanism. This is a case where I personally prefer an out of band confirmation. However, I understand the convenience of trust-on-first-use, and It's Probably Fine™.

Would you be willing to tweak this so that if the thumbprint_list variable is null then the module falls back on reading the value from the TLS certificate chain? That would allow paranoid people like me to continue using an out of band method (and prevent this from being a breaking change!) while also supporting trust-on-first-use for those who prefer the convenience. I'd happily merge that enhancement 👍

**Comment by TonyLovesDevOps** [comment]
@AlexSc I think this is a good idea. I made the requested changes for the tinfoil hat types (gotta love and support them)!

**Comment by AlexSc** [comment]
Thanks @TonyLovesDevOps!

I'll include a special thanks to you in the changelog -- would you like that to link to your GitHub profile, a homepage, LinkedIn, or something else?

**Comment by TonyLovesDevOps** [comment]
> Thanks @TonyLovesDevOps!
> 
> I'll include a special thanks to you in the changelog -- would you like that to link to your GitHub profile, a homepage, LinkedIn, or something else?

Thank you! A link to my GitHub profile would be much appreciated.

**Comment by AlexSc** [comment]
0.1.2 has now shipped with your contribution 🎉

**Pull request merged**
